package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"text/template"
)

// Source of HMS error-code data
const HMS_ERR_CODE_URL = "https://raw.githubusercontent.com/bambulab/BambuStudio/refs/heads/master/resources/hms"

var HMS_ERR_CODE_FILES = []string{
	"hms_en_093.json",
	"hms_en_094.json",
	"hms_en_20P.json",
	"hms_en_22E.json",
	"hms_en_239.json",
	"hms_en_26A.json",
	"hms_en_31B.json",
}

// HmsECodeRecords represents a list of HMS error codes and their corresponding explanations.
type HmsECodeRecords []struct {
	Ecode string `json:"ecode"`
	Intro string `json:"intro"`
}

// Used to populate the go file containing a map of the HmsErrors
const hmsGoTemplate = `// Code generated by "./../../scripts/update_hms_err_codes.sh"; DO NOT EDIT.
package hms

var HmsErrors = map[string]string{
	{{- range .}}
	"{{ .Ecode }}": "{{ .Intro}}",
	{{- end }}
}
`

// Gather pulls each [HMS_ERR_CODE_FILES] from [HMS_ERR_CODE_URL], and populates [HmsECodeRecords] with all the "ecode"/"intro" pairs contained in each response.
func (hmsRecords *HmsECodeRecords) Gather() error {
	var hmsResp HmsResp

	for _, json_file := range HMS_ERR_CODE_FILES {
		resp, err := http.Get(fmt.Sprintf("%s/%s", HMS_ERR_CODE_URL, json_file))
		if err != nil {
			return err
		}
		defer resp.Body.Close()
		if err := json.NewDecoder(resp.Body).Decode(&hmsResp); err != nil {
			return err
		}
		*hmsRecords = append(*hmsRecords, hmsResp.Data.DeviceHms.HmsECodeRecords...)
	}
	return nil
}

// Dump injects the contents of [HmsECodeRecords] into a Go template and writes the generated content to an [io.Writer].
func (r HmsECodeRecords) Dump(tmplStr string, w io.Writer) error {
	var err error
	tmpl := template.New("tmplStr")

	if tmpl, err = tmpl.Parse(hmsGoTemplate); err != nil {
		return err
	}
	if err := tmpl.Execute(w, r); err != nil {
		return err
	}
	return nil
}

// HmsResp represents a collection of HMS (Health Management System) records extracted from [HMS_ERR_CODE_FILES] located at [HMS_ERR_CODE_URL].
// Most fields not needed to populate [HmsECodeRecords] have been omitted,
// however some, such as [HmsResp.Timestamp] and [HmsResp.Version], are retained
// as these serve as useful sources of metadata that we may want to make use of.
type HmsResp struct {
	Timestamp int `json:"t"`
	Version   int `json:"ver"`
	Data      struct {
		DeviceHms struct {
			HmsECodeRecords `json:"records"`
		} `json:"device_hms"`
	} `json:"data"`
}

func main() {
	// Query endpoints to populate hms error records
	var records HmsECodeRecords
	if err := records.Gather(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// Sanitise Intro strings
	for i := 0; i < len(records); i++ {
		records[i].Intro = strings.ReplaceAll(records[i].Intro, "\"", "\\\"")
	}

	// Populate template and dump to stdout
	if err := records.Dump(hmsGoTemplate, os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
