package main

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path"
	"text/template"
	"time"

	"golang.org/x/sync/errgroup"
)

const (
	// Source of HMS error-code data
	HMS_ERR_CODE_URL = "https://raw.githubusercontent.com/bambulab/BambuStudio/refs/heads/master/resources/hms"
	// Max time we will wait before giving up on a HTTP request
	REQUEST_TIMEOUT = 2 * time.Second
	// File being written to with the populated [HMS_GO_TEMPLATE]
	TARGET_FILE_PATH = "./internal/hms/errors.go"
	// replace empty Intro strings with placeholder
	INTRO_MISSING_PLACEHOLDER = "\"<MISSING>\""
)

// HMS_ERR_CODE_FILES are located at [HMS_ERR_CODE_URL],
// and are the names of JSON files containing HMS error codes with english-text intro text.
// The suffix codes in the file-names (e.g. _093, _094, _20P, ...) correspond to the prefixes of certain
// Bambu Lab 3D printers according to: https://wiki.bambulab.com/en/general/find-sn.
var HMS_ERR_CODE_FILES = []string{
	"hms_en_093.json", // H2S
	"hms_en_094.json", // H2D
	"hms_en_20P.json", // X2D
	"hms_en_22E.json", // 22E
	"hms_en_239.json", // H2D Pro
	"hms_en_26A.json", // A2L
	"hms_en_31B.json", // H2C
}

// HmsECodeRecords represents a list of HMS error codes and their corresponding explanations.
type HmsECodeRecords []struct {
	Ecode string `json:"ecode"`
	Intro string `json:"intro"`
}

// Used to populate the go file containing a map of the HmsErrors
const HMS_GO_TEMPLATE = `// Code generated by "./../../scripts/update_hms_err_codes.sh"; DO NOT EDIT.
package hms

var HmsErrors = map[string]string{
	{{- range $key, $val := .}}
	"{{ $key }}": {{ $val }},
	{{- end }}
}
`

// Gather pulls each [HMS_ERR_CODE_FILES] from [HMS_ERR_CODE_URL], and populates [HmsECodeRecords] with all the "ecode"/"intro" pairs contained in each response.
func (hmsRecords *HmsECodeRecords) Gather(ctx context.Context, url string) error {
	// formulate the request for the given json file
	var hmsResp HmsResp
	req, err := http.NewRequestWithContext(ctx, "GET", url, nil)
	if err != nil {
		return err
	}
	// perform query and populate response struct
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if err := json.NewDecoder(resp.Body).Decode(&hmsResp); err != nil {
		return err
	}
	// only keep HMS error-code records from response struct
	*hmsRecords = append(*hmsRecords, hmsResp.Data.DeviceHms.HmsECodeRecords...)
	return nil
}

// Dump injects the contents of [HmsECodeRecords] into a Go template and writes the generated content to an [io.Writer].
func Dump(tmplStr string, hms map[string]string, w io.Writer) error {
	tmpl, err := template.New("tmplStr").Parse(HMS_GO_TEMPLATE)
	if err != nil {
		return err
	}

	if err := tmpl.Execute(w, hms); err != nil {
		return err
	}
	return nil
}

// HmsResp represents a collection of HMS (Health Management System) records extracted from [HMS_ERR_CODE_FILES] located at [HMS_ERR_CODE_URL].
// Most fields not needed to populate [HmsECodeRecords] have been omitted,
// however some, such as [HmsResp.Timestamp] and [HmsResp.Version], are retained
// as these serve as useful sources of metadata that we may want to make use of.
type HmsResp struct {
	Timestamp int `json:"t"`
	Version   int `json:"ver"`
	Data      struct {
		DeviceHms struct {
			HmsECodeRecords `json:"en"`
		} `json:"device_hms"`
	} `json:"data"`
}

func main() {
	// create the target file and a corresponding writer
	root, err := os.Getwd()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	f, err := os.Create(path.Join(root, TARGET_FILE_PATH))
	if err != nil {
		panic(err)
	}
	log.Printf("Successfully created '%s' to receive populated template", TARGET_FILE_PATH)
	defer f.Close()
	w := bufio.NewWriter(f)

	// synchronise HMS data from different sources, ensuring any error prevents further execution
	ch := make(chan HmsECodeRecords, len(HMS_ERR_CODE_FILES))
	_ctx, cancel := context.WithTimeout(context.Background(), REQUEST_TIMEOUT)
	defer cancel()

	errGroup, ctx := errgroup.WithContext(_ctx)

	// concurrently query endpoints to populate hms error records; error from any endpoint causes early exit
	for _, json_file := range HMS_ERR_CODE_FILES {
		errGroup.Go(func() error {
			var records HmsECodeRecords
			url := fmt.Sprintf("%s/%s", HMS_ERR_CODE_URL, json_file)
			if err := records.Gather(ctx, url); err != nil {
				return err
			}
			log.Printf("Successfully pulled %d HMS records from '%s'", len(records), url)
			ch <- records
			return nil
		})
	}
	if err := errGroup.Wait(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// aggregate and sanitise response content:
	var totalRecords HmsECodeRecords
	for range HMS_ERR_CODE_FILES {
		totalRecords = append(totalRecords, <-ch...)
	}
	log.Printf("Gathered %d HMS records in total", len(totalRecords))

	outputHmsRecords := make(map[string]string)
	for _, record := range totalRecords {
		// drop records with missing info-text
		if len(record.Intro) == 0 {
			outputHmsRecords[record.Ecode] = INTRO_MISSING_PLACEHOLDER
			continue
		}
		// parse intro as json string to retain escape chars
		intro, err := json.Marshal(record.Intro)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		outputHmsRecords[record.Ecode] = string(intro)
	}

	// Populate template and dump to stdout
	if err := Dump(HMS_GO_TEMPLATE, outputHmsRecords, w); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	w.Flush()
	os.Exit(0)
}
