package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"text/template"
)

const (
	WIKI_URL    = "https://wiki.bambulab.com/en/hms/home"
	JSON_URL    = "https://e.bambulab.com/wikijs/GetHmsWikiList.php"
	MAX_RECORDS = 1_000 // each resp will only contain up-to this many hms records
	MAX_PAGES   = 10    // each resp corresponds to a "page"; limits number of requests
)

// HmsECodeRecord represents a single Hms error code (fields not needed for scraping logic have been omitted).
type HmsECodeRecord struct {
	Ecode string `json:"ecode"`
	Intro string `json:"intro"`
}

type HmsECodeRecords []HmsECodeRecord

// used to populate the go file containing a map of the HmsErrors
const hmsGoTemplate = `// Code generated by "./../../scripts/update_hms_err_codes.sh"; DO NOT EDIT.
package hms

var HmsErrors = map[string]string{
	{{- range .}}
	"{{ .Ecode }}": "{{ .Intro}}",
	{{- end }}
}
`

// Gather scrapes the [JSON_URL] for records containing hms error codes
// and builds up a cumulative list of [HmsECodeRecords] from each consecutive response.
// Each response from [JSON_URL] is limited to returning [MAX_RECORDS] [HmsECodeRecord] entries,
// so the url-param is incremented until either [MAX_PAGES] is reached, or the
// total number of records scraped matches the expected total number of records.
func (hmsRecords *HmsECodeRecords) Gather() error {
	page := 1        // start reading hms records from first page
	recordTotal := 0 // this can only be known after first response

	var hmsResp HmsResp

	for page < MAX_PAGES {
		resp, err := http.Get(fmt.Sprintf("%s?size=%d&page=%d", JSON_URL, MAX_RECORDS, page))
		if err != nil {
			return err
		}
		defer resp.Body.Close()
		if err := json.NewDecoder(resp.Body).Decode(&hmsResp); err != nil {
			return err
		}
		*hmsRecords = append(*hmsRecords, hmsResp.Data.Records...)
		if recordTotal = hmsResp.Data.Total; len(*hmsRecords) >= recordTotal {
			return nil
		}
		if recordTotal > MAX_PAGES*MAX_RECORDS {
			missingPages := float64(recordTotal)/float64(MAX_RECORDS) - MAX_PAGES
			return fmt.Errorf("Must increase MAX_PAGES by %f to scrape all records (%d)", missingPages, recordTotal)
		}
		page += 1
	}
	return fmt.Errorf("Scraped more records than expected total")
}

// Dump injects the contents of HmsECodeRecords into a Go template,
// and the resulting content is handed over to an io.Writer.
func (r HmsECodeRecords) Dump(tmplStr string, w io.Writer) error {
	var err error
	tmpl := template.New("tmplStr")

	if tmpl, err = tmpl.Parse(hmsGoTemplate); err != nil {
		return err
	}
	if err := tmpl.Execute(w, r); err != nil {
		return err
	}
	return nil
}

// HmsResp represents a collection of Health Management System records returned
// by the REST API [JSON_URL] that's used to populate hms entries in the wiki [WIKI_URL]
// (fields not needed for scraping logic have been omitted).
type HmsResp struct {
	Timestamp int `json:"t"`
	Data      struct {
		Page    int             `json:"page"`
		Size    int             `json:"size"`
		Total   int             `json:"total"`
		Records HmsECodeRecords `json:"records"`
	} `json:"data"`
}

func main() {
	// query API endpoint to populate hms error records
	var records HmsECodeRecords
	if err := records.Gather(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// sanitise Intro strings
	for i := 0; i < len(records); i++ {
		records[i].Intro = strings.ReplaceAll(records[i].Intro, "\"", "\\\"")
	}

	// populate template and dump to stdout
	if err := records.Dump(hmsGoTemplate, os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
