"""
Bambulabs HMS error parser

HMS errors update frequently so the aim of this script to parse them
and generate a golang file containing the error codes and messages.

https://wiki.bambulab.com/en/hms/home

requires: beautifulsoup4, requests
"""

import json
from pathlib import Path
from typing import Any, Dict

import requests
from bs4 import BeautifulSoup

URL = "https://wiki.bambulab.com/en/hms/home"

ROOT = Path(__file__).resolve().parent.parent
OUT_FILE_PATH = ROOT / "hms" / "errors.go"


def parse_hms_error_blockquote(bq) -> Dict[str, Any]:
    result = {"code": None, "message": None, "synonyms": []}

    main_p = bq.find("p")
    if main_p is None:
        return result

    strong = main_p.find("strong")
    if strong is None:
        return result

    # weird workaround to get text content
    content = strong.encode_contents().decode("utf-8")
    if ":" not in content:
        return result

    code, message = content.split(":", 1)
    result["code"] = code.strip()
    result["message"] = message.strip()

    syn_p = bq.find_all("p")
    if len(syn_p) > 1:
        syn_small = syn_p[1].find("small")
        if syn_small:
            result["synonyms"] = (
                syn_small.encode_contents().decode("utf-8").strip().split(",")
            )

    return result


def go_escape(s: str) -> str:
    return json.dumps(s)[1:-1]


def generate_error_map(parsed, package_name) -> str:
    dedup = {}

    for item in parsed:
        code = item.get("code")
        msg = item.get("message")

        if code is not None and msg is not None:
            dedup[code] = msg

    result = [
        "// Code generated by hms.py; DO NOT EDIT.",
        f"package {package_name}",
        "",
        "var HmsErrors = map[string]string{",
    ]

    for code, msg in dedup.items():
        result.append(f'\t"{go_escape(code)}": "{go_escape(msg)}",')

    result.append("}")
    return "\n".join(result)


def main():
    response = requests.get(URL)
    soup = BeautifulSoup(response.content, "html.parser")

    block_quotes = soup.find_all("blockquote")
    parsed = [parse_hms_error_blockquote(bq) for bq in block_quotes[2:]]
    error_map = generate_error_map(parsed, "hms")

    with open(OUT_FILE_PATH, "w") as f:
        f.write(error_map)


if __name__ == "__main__":
    main()
